# Site
repository: iAmPWN/iAmPWN.github.io
favicon: images/favicon.ico

# Personal info
name: Pawan Kumar
title: Data Engineer
email: iAmPWN@outlook.com
website: www.iAmPWN.com

# Social links
twitter_username: pawan315
github_username:  iAmPWN
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: pwn315
linkedin_username: iAmPWN
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pawan and I'm a a passionate Data engineer, self-driven individual contributor and a team player with a proven passion for developing technical solutions (end-to-end data solution) to generate data insights in an agile process and environment.

  I am most skilled in: <mark>Business Intelligence</mark> and <mark>Data Engineering</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data engineering some of my other interests and hobbies are:
   - Gaming
   - Photography

# Footer
footer_show_references: true

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
